# NumPy Arrays
### Python objects:

1. High-level number objects: integers, floating point
2. Containers:     lists (costless insertion and append)....and..... Dictionaries (Fast lookup)
                 
### * Numpy is the fundamental package for scientific computing with Python.
#### NumPy provides:
 1. Extension package to Python for multi-dimensional arrays
 2. Closer to hardware (Efficiency)
 3. Designed for scientific computation (convenience)
 4. Also known as Array Oriented Computing

## Importing NumPy Module

In [5]:
import numpy # or
import numpy as np

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
np.array([1,2,3,4.2])

array([1. , 2. , 3. , 4.2])

### For NumPy, the default datatype is float.

In [8]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [9]:
type(a)

numpy.ndarray

In [10]:
p=np.array([1,2,3,4.2])
p

array([1. , 2. , 3. , 4.2])

In [11]:
type(p)

numpy.ndarray

In [12]:
p.dtype

dtype('float64')

In [13]:
a.dtype

dtype('int32')

In [14]:
from numpy import array as arr

In [15]:
d2= arr([[1,2,3,4]])
d2

array([[1, 2, 3, 4]])

In [16]:
ar2=np.arange(100)
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
ar2= np.arange(5,100,5)
ar2

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [18]:
len(ar2)

19

In [19]:
ar2.shape  #To know the number of rows and columns

(19,)

In [20]:
ar3= np.arange(1,10)
ar3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
re=ar3.reshape(3,3)

In [22]:
ar3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
m=np.zeros(50)
m

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
m.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [26]:
li1=[1,2,3,4,5,6]
li2=[6,5,4,3,2,1]

for i in range(0,len(li1)):
    print(li1[i]+li2[i])

7
7
7
7
7
7


In [27]:
li=[]
for i in range(0,100):
    li.append(i)

print(li)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [28]:
li2=li.copy()

In [29]:
li2.reverse()

In [30]:
# Python LISTS
x=[]
for i in range(0,len(li)):
    %timeit li[i]+li2[i]

153 ns ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
149 ns ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


KeyboardInterrupt: 

In [31]:
m=np.arange(1,100)
n=np.arange(100,1,-1)
%timeit m+n                # timeit gives us the total time taken to for the execution of a loop..."arange" function is very fast wrt lists

583 ns ± 41.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [32]:
ar5= np.arange(0,10)               # dimensions neednot be equal but the lengths must be equal
ar6=np.arange(10,20)
ar5+ar6

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [33]:
ar5*ar6

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [34]:
ar6.max()    # To know the greatest number of an array

19

In [35]:
ar6.min()    # To know the smallest number of an array

10

In [36]:
ar5>ar6

array([False, False, False, False, False, False, False, False, False,
       False])

In [37]:
ar7= arr([55,11,34,54,5,34,23,7,133,171])
ar6<ar7

array([ True, False,  True,  True, False,  True,  True, False,  True,
        True])

In [38]:
ar7[0]

55

In [39]:
ar7[-1]

171

In [40]:
ar7[0:6]

array([55, 11, 34, 54,  5, 34])

In [41]:
ar7[0:5] = 0
ar7

array([  0,   0,   0,   0,   0,  34,  23,   7, 133, 171])

In [42]:
ar7[-1] = 0
ar7

array([  0,   0,   0,   0,   0,  34,  23,   7, 133,   0])

In [43]:
ar7>ar6

array([False, False, False, False, False,  True,  True, False,  True,
       False])

In [44]:
ar7[ar7>ar6]

array([ 34,  23, 133])

In [45]:
ar7.mean()    # mean of all elements in ar7

19.7

In [46]:
ar7.sum()     # sum of all elements in ar7

197

In [47]:
ar7.max()

133

In [48]:
ar7.argmax()   # position of greatest number in ar7

8

In [49]:
ar7.min()

0

In [50]:
ar7.argmin()   # position of smallest number in ar7

0

In [51]:
ar7.ndim      # to know the dimension of an array

1